/** accessoires du Concours Pokémon (Diamant/Perle), sprites dans public/sprites/cosmetics */

export type CosmeticCategory = "tete" | "nature" | "effets" | "objets" | "scene"

export type Cosmetic = {
  id: string
  label: string
  category: CosmeticCategory
  /** taille native du sprite, en px */
  width: number
  height: number
  /** placé derrière le Pokémon par défaut (décors) */
  back?: boolean
}

export const COSMETIC_CATEGORIES: { id: CosmeticCategory; label: string }[] = [
  { id: "tete", label: "Tête & visage" },
  { id: "nature", label: "Nature" },
  { id: "effets", label: "Effets" },
  { id: "objets", label: "Objets" },
  { id: "scene", label: "Décors" },
]

// prettier-ignore
export const COSMETICS: Cosmetic[] = [
  { id: "award-podium", label: "Podium", category: "scene", width: 62, height: 24, back: true },
  { id: "big-leaf", label: "Grande Feuille", category: "nature", width: 20, height: 20 },
  { id: "big-scale", label: "Grande Écaille", category: "nature", width: 20, height: 16 },
  { id: "big-tree", label: "Grand Arbre", category: "scene", width: 32, height: 46, back: true },
  { id: "black-beard", label: "Barbe Noire", category: "tete", width: 5, height: 16 },
  { id: "black-fluff", label: "Duvet Noir", category: "nature", width: 12, height: 12 },
  { id: "black-moustache", label: "Moustache Noire", category: "tete", width: 15, height: 6 },
  { id: "black-pebble", label: "Caillou Noir", category: "nature", width: 14, height: 14 },
  { id: "black-specs", label: "Lunettes Noires", category: "tete", width: 24, height: 8 },
  { id: "blue-balloons", label: "Ballons Bleus", category: "objets", width: 32, height: 62 },
  { id: "blue-barrette", label: "Barrette Bleue", category: "tete", width: 17, height: 18 },
  { id: "blue-feather", label: "Plume Bleue", category: "nature", width: 13, height: 13 },
  { id: "blue-flower", label: "Fleur Bleue", category: "nature", width: 13, height: 13 },
  { id: "blue-scale", label: "Écaille Bleue", category: "nature", width: 7, height: 15 },
  { id: "brown-fluff", label: "Duvet Marron", category: "nature", width: 13, height: 13 },
  { id: "cape", label: "Cape", category: "tete", width: 50, height: 32 },
  { id: "carpet", label: "Tapis Volant", category: "scene", width: 59, height: 28, back: true },
  { id: "chimchar-mask", label: "Masque Ouisticram", category: "tete", width: 32, height: 32 },
  { id: "colored-parasol", label: "Ombrelle Colorée", category: "objets", width: 31, height: 57 },
  { id: "comet-piece-1", label: "Éclat de Comète 1", category: "effets", width: 5, height: 5 },
  { id: "comet-piece-2", label: "Éclat de Comète 2", category: "effets", width: 5, height: 5 },
  { id: "comet-piece-3", label: "Éclat de Comète 3", category: "effets", width: 6, height: 6 },
  { id: "comet-piece-4", label: "Éclat de Comète 4", category: "effets", width: 6, height: 6 },
  { id: "comet-piece-5", label: "Éclat de Comète 5", category: "effets", width: 13, height: 12 },
  { id: "comet", label: "Comète", category: "effets", width: 38, height: 31 },
  { id: "confetti-1", label: "Confettis 1", category: "effets", width: 8, height: 8 },
  { id: "confetti-2", label: "Confettis 2", category: "effets", width: 7, height: 6 },
  { id: "confetti-3", label: "Confettis 3", category: "effets", width: 7, height: 5 },
  { id: "confetti-4", label: "Confettis 4", category: "effets", width: 11, height: 11 },
  { id: "confetti-5", label: "Confettis 5", category: "effets", width: 5, height: 4 },
  { id: "confetti-6", label: "Confettis 6", category: "effets", width: 6, height: 6 },
  { id: "confetti-7", label: "Confettis 7", category: "effets", width: 5, height: 6 },
  { id: "confetti-8", label: "Confettis 8", category: "effets", width: 6, height: 5 },
  { id: "confetti-9", label: "Confettis 9", category: "effets", width: 9, height: 8 },
  { id: "crown", label: "Couronne", category: "tete", width: 26, height: 21 },
  { id: "cube-stage", label: "Scène Cube", category: "scene", width: 35, height: 32, back: true },
  { id: "determination", label: "Détermination", category: "effets", width: 63, height: 32 },
  { id: "eerie-thing-small", label: "Petit Truc Étrange", category: "effets", width: 11, height: 9 },
  { id: "eerie-thing", label: "Truc Étrange", category: "effets", width: 26, height: 21 },
  { id: "flag", label: "Drapeau", category: "objets", width: 28, height: 43 },
  { id: "flower-stage", label: "Scène Fleurie", category: "scene", width: 45, height: 32, back: true },
  { id: "fluffy-bed", label: "Lit Douillet", category: "scene", width: 63, height: 32, back: true },
  { id: "glass-stage", label: "Scène de Verre", category: "scene", width: 45, height: 23, back: true },
  { id: "glitter-boulder", label: "Rocher Scintillant", category: "nature", width: 20, height: 20 },
  { id: "glitter-powder-1", label: "Poudre Scintillante 1", category: "effets", width: 7, height: 8 },
  { id: "glitter-powder-2", label: "Poudre Scintillante 2", category: "effets", width: 7, height: 8 },
  { id: "glitter-powder-3", label: "Poudre Scintillante 3", category: "effets", width: 5, height: 5 },
  { id: "glitter-powder-4", label: "Poudre Scintillante 4", category: "effets", width: 7, height: 8 },
  { id: "glitter-powder-5", label: "Poudre Scintillante 5", category: "effets", width: 5, height: 5 },
  { id: "glitter-powder-6", label: "Poudre Scintillante 6", category: "effets", width: 5, height: 5 },
  { id: "glitter-powder-7", label: "Poudre Scintillante 7", category: "effets", width: 7, height: 8 },
  { id: "glitter-powder-8", label: "Poudre Scintillante 8", category: "effets", width: 5, height: 5 },
  { id: "glitter-powder-9", label: "Poudre Scintillante 9", category: "effets", width: 5, height: 5 },
  { id: "glitter-powder-10", label: "Poudre Scintillante 10", category: "effets", width: 5, height: 5 },
  { id: "glitter-powder-11", label: "Poudre Scintillante 11", category: "effets", width: 7, height: 8 },
  { id: "glitter-powder-12", label: "Poudre Scintillante 12", category: "effets", width: 7, height: 8 },
  { id: "gold-pedestal", label: "Piédestal Doré", category: "scene", width: 38, height: 21, back: true },
  { id: "googly-specs", label: "Lunettes Rigolotes", category: "tete", width: 22, height: 10 },
  { id: "gorgeous-specs", label: "Lunettes Chic", category: "tete", width: 23, height: 8 },
  { id: "green-balloons", label: "Ballons Verts", category: "objets", width: 32, height: 60 },
  { id: "green-barrette", label: "Barrette Verte", category: "tete", width: 19, height: 18 },
  { id: "green-scale", label: "Écaille Verte", category: "nature", width: 12, height: 12 },
  { id: "heroic-headband", label: "Bandeau Héroïque", category: "tete", width: 23, height: 13 },
  { id: "humming-note", label: "Note de Musique", category: "effets", width: 22, height: 20 },
  { id: "jagged-boulder", label: "Rocher Pointu", category: "nature", width: 23, height: 20 },
  { id: "lace-headdress", label: "Coiffe en Dentelle", category: "tete", width: 48, height: 32 },
  { id: "mini-pebble", label: "Mini Caillou", category: "nature", width: 10, height: 8 },
  { id: "mirror-ball-sparkle-1", label: "Reflet Disco 1", category: "effets", width: 5, height: 6 },
  { id: "mirror-ball-sparkle-2", label: "Reflet Disco 2", category: "effets", width: 31, height: 35 },
  { id: "mirror-ball-sparkle-3", label: "Reflet Disco 3", category: "effets", width: 7, height: 7 },
  { id: "mirror-ball", label: "Boule Disco", category: "objets", width: 7, height: 8 },
  { id: "mystic-fire-1", label: "Feu Mystique 1", category: "effets", width: 6, height: 15 },
  { id: "mystic-fire-2", label: "Feu Mystique 2", category: "effets", width: 9, height: 13 },
  { id: "mystic-fire-3", label: "Feu Mystique 3", category: "effets", width: 11, height: 19 },
  { id: "mystic-fire-4", label: "Feu Mystique 4", category: "effets", width: 6, height: 15 },
  { id: "narrow-leaf", label: "Feuille Fine", category: "nature", width: 21, height: 10 },
  { id: "narrow-scale", label: "Écaille Fine", category: "nature", width: 7, height: 20 },
  { id: "old-umbrella", label: "Vieux Parapluie", category: "objets", width: 31, height: 48 },
  { id: "orange-flower", label: "Fleur Orange", category: "nature", width: 14, height: 14 },
  { id: "orange-fluff", label: "Duvet Orange", category: "nature", width: 13, height: 13 },
  { id: "peculiar-spoon", label: "Cuillère Tordue", category: "objets", width: 11, height: 25 },
  { id: "photo-board", label: "Panneau Photo", category: "scene", width: 32, height: 64, back: true },
  { id: "pink-balloon", label: "Ballon Rose", category: "objets", width: 24, height: 44 },
  { id: "pink-barrette", label: "Barrette Rose", category: "tete", width: 13, height: 9 },
  { id: "pink-flower", label: "Fleur Rose", category: "nature", width: 13, height: 13 },
  { id: "pink-fluff", label: "Duvet Rose", category: "nature", width: 12, height: 12 },
  { id: "pink-scale", label: "Écaille Rose", category: "nature", width: 11, height: 9 },
  { id: "piplup-mask", label: "Masque Tiplouf", category: "tete", width: 31, height: 25 },
  { id: "poison-extract", label: "Extrait de Poison", category: "objets", width: 26, height: 12 },
  { id: "pretty-dewdrop", label: "Jolie Rosée", category: "nature", width: 9, height: 13 },
  { id: "professor-hat", label: "Toque de Diplômé", category: "tete", width: 27, height: 18 },
  { id: "puffy-smoke", label: "Fumée", category: "effets", width: 52, height: 30 },
  { id: "purple-scale", label: "Écaille Violette", category: "nature", width: 12, height: 10 },
  { id: "red-balloons", label: "Ballons Rouges", category: "objets", width: 32, height: 59 },
  { id: "red-barrette", label: "Barrette Rouge", category: "tete", width: 21, height: 15 },
  { id: "red-feather", label: "Plume Rouge", category: "nature", width: 13, height: 13 },
  { id: "red-flower", label: "Fleur Rouge", category: "nature", width: 15, height: 15 },
  { id: "retro-pipe", label: "Tuyau Rétro", category: "objets", width: 51, height: 23 },
  { id: "round-pebble", label: "Caillou Rond", category: "nature", width: 11, height: 11 },
  { id: "seashell", label: "Coquillage", category: "nature", width: 11, height: 10 },
  { id: "shed-claw", label: "Griffe Tombée", category: "nature", width: 7, height: 9 },
  { id: "shed-horn", label: "Corne Tombée", category: "nature", width: 11, height: 19 },
  { id: "shimmering-fire-1", label: "Feu Chatoyant 1", category: "effets", width: 8, height: 11 },
  { id: "shimmering-fire-2", label: "Feu Chatoyant 2", category: "effets", width: 9, height: 10 },
  { id: "shimmering-fire-3", label: "Feu Chatoyant 3", category: "effets", width: 20, height: 25 },
  { id: "shimmering-fire-4", label: "Feu Chatoyant 4", category: "effets", width: 10, height: 12 },
  { id: "shimmering-fire-5", label: "Feu Chatoyant 5", category: "effets", width: 6, height: 10 },
  { id: "shiny-powder-1", label: "Poudre Brillante 1", category: "effets", width: 3, height: 3 },
  { id: "shiny-powder-2", label: "Poudre Brillante 2", category: "effets", width: 3, height: 3 },
  { id: "silk-veil", label: "Voile de Soie", category: "tete", width: 58, height: 32 },
  { id: "small-leaf", label: "Petite Feuille", category: "nature", width: 15, height: 15 },
  { id: "snaggy-pebble", label: "Caillou Crochu", category: "nature", width: 8, height: 8 },
  { id: "snow-crystal", label: "Cristal de Neige", category: "nature", width: 17, height: 17 },
  { id: "sparks-1", label: "Étincelles 1", category: "effets", width: 8, height: 7 },
  { id: "sparks-2", label: "Étincelles 2", category: "effets", width: 14, height: 10 },
  { id: "sparks-3", label: "Étincelles 3", category: "effets", width: 9, height: 10 },
  { id: "sparks-4", label: "Étincelles 4", category: "effets", width: 8, height: 7 },
  { id: "sparks-5", label: "Étincelles 5", category: "effets", width: 6, height: 5 },
  { id: "spotlight", label: "Projecteur", category: "scene", width: 32, height: 64, back: true },
  { id: "spring", label: "Ressort", category: "objets", width: 13, height: 14 },
  { id: "standing-mike", label: "Micro sur Pied", category: "objets", width: 30, height: 56 },
  { id: "stump", label: "Souche", category: "scene", width: 44, height: 24, back: true },
  { id: "surfboard", label: "Planche de Surf", category: "objets", width: 60, height: 15 },
  { id: "sweet-candy", label: "Bonbon", category: "objets", width: 19, height: 19 },
  { id: "thick-mushroom", label: "Gros Champignon", category: "nature", width: 16, height: 14 },
  { id: "thin-mushroom", label: "Champignon Fin", category: "nature", width: 7, height: 15 },
  { id: "tiara", label: "Tiare", category: "tete", width: 23, height: 13 },
  { id: "top-hat", label: "Haut-de-Forme", category: "tete", width: 24, height: 26 },
  { id: "turtwig-mask", label: "Masque Tortipouss", category: "tete", width: 28, height: 29 },
  { id: "wealthy-coin-1", label: "Pièce Fortune 1", category: "objets", width: 12, height: 25 },
  { id: "wealthy-coin-2", label: "Pièce Fortune 2", category: "objets", width: 11, height: 8 },
  { id: "wealthy-coin-3", label: "Pièce Fortune 3", category: "objets", width: 7, height: 12 },
  { id: "wealthy-coin-4", label: "Pièce Fortune 4", category: "objets", width: 12, height: 16 },
  { id: "wealthy-coin-5", label: "Pièce Fortune 5", category: "objets", width: 12, height: 10 },
  { id: "white-beard", label: "Barbe Blanche", category: "tete", width: 22, height: 20 },
  { id: "white-feather", label: "Plume Blanche", category: "nature", width: 13, height: 13 },
  { id: "white-flower", label: "Fleur Blanche", category: "nature", width: 14, height: 17 },
  { id: "white-fluff", label: "Duvet Blanc", category: "nature", width: 13, height: 13 },
  { id: "white-moustache", label: "Moustache Blanche", category: "tete", width: 16, height: 8 },
  { id: "yellow-balloon", label: "Ballon Jaune", category: "objets", width: 24, height: 59 },
  { id: "yellow-barrette", label: "Barrette Jaune", category: "tete", width: 17, height: 16 },
  { id: "yellow-feather", label: "Plume Jaune", category: "nature", width: 13, height: 13 },
  { id: "yellow-flower", label: "Fleur Jaune", category: "nature", width: 13, height: 13 },
  { id: "yellow-fluff", label: "Duvet Jaune", category: "nature", width: 12, height: 12 },
]

export const COSMETICS_BY_ID = new Map(COSMETICS.map((c) => [c.id, c]))

export const cosmeticUrl = (id: string) => `/sprites/cosmetics/${id}.png`
